import { useState, useEffect } from 'react';
import ReactMarkdown from 'react-markdown';
import { formatDistanceToNow } from 'date-fns';
import { Sparkles, AlertCircle, Clock, RefreshCw, Activity } from 'lucide-react';
import { useAiInsight, useRefreshAiInsight } from '../../hooks/useAiInsight';
import { useAiChat } from '../../hooks/useAiChat';
import AiChatBox from '../../components/ai/AiChatBox';
import MonthYearPicker from '../../components/common/MonthYearPicker';

/**
 * AI Insight Page
 * Displays financial advice and analysis generated by Google Gemini
 */
const AiInsightPage = () => {
  const currentDate = new Date();
  const [month, setMonth] = useState(currentDate.getMonth() + 1);
  const [year, setYear] = useState(currentDate.getFullYear());

  // Typing effect state
  const [displayedText, setDisplayedText] = useState('');
  const [isTyping, setIsTyping] = useState(false);

  // Queries and Mutations
  const { data: responseData, isLoading, isError, error } = useAiInsight(month, year);
  const refreshMutation = useRefreshAiInsight();

  const insightData = responseData?.data;
  const isRefreshing = refreshMutation.isPending;

  // Chat Mutation
  const chatMutation = useAiChat();

  const handleSendMessage = (message, onAiReply) => {
    chatMutation.mutate(
      { message, month, year },
      {
        onSuccess: (response) => {
          // Extract AI response from different possible structures
          // 1. response.data.aiResponse (Standard Dto wrapper)
          // 2. response.data (Direct string in data field)
          // 3. response.aiResponse (Direct Dto)
          const aiText = response?.data?.aiResponse || (typeof response?.data === 'string' ? response.data : null) || response?.aiResponse;
          
          if (aiText) {
            onAiReply(aiText);
          }
        },
      }
    );
  };

  // Handlers
  const handleDateChange = ({ month: newMonth, year: newYear }) => {
    setMonth(newMonth);
    setYear(newYear);
    // Reset typing effect on date change
    setDisplayedText('');
    setIsTyping(false);
  };

  const handleRefresh = () => {
    setDisplayedText('');
    setIsTyping(false);
    refreshMutation.mutate({ month, year });
  };

  // Typing Effect Logic
  useEffect(() => {
    if (insightData?.aiResponse && !isLoading && !isRefreshing) {
      setIsTyping(true);
      let i = 0;
      const fullText = insightData.aiResponse;
      setDisplayedText(''); // clear previous

      // Speed up typing to avoid taking too long for large markdown
      const speed = Math.max(5, Math.floor(100 / (fullText.length / 50))); 
      
      const intervalId = setInterval(() => {
        setDisplayedText(fullText.substring(0, i));
        i += 3; // add chunks of chars to make it faster
        if (i > fullText.length) {
          clearInterval(intervalId);
          setDisplayedText(fullText); // ensure full text is set
          setIsTyping(false);
        }
      }, speed);

      return () => clearInterval(intervalId);
    }
  }, [insightData?.aiResponse, isLoading, isRefreshing]);

  // Check if error is due to "No transactions" (Assuming BE returns 404 or specific code for empty month)
  const isNoDataError = error?.response?.status === 404 || error?.response?.data?.message?.includes('not enough data');

  return (
    <div className="space-y-6 max-w-5xl mx-auto pb-10 animate-in fade-in duration-500">
      
      {/* Header Section */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 bg-white p-5 rounded-2xl shadow-sm border border-gray-100">
        <div className="flex items-center gap-4">
          <div className="w-14 h-14 rounded-2xl bg-gradient-to-tr from-indigo-500 via-purple-500 to-pink-500 flex items-center justify-center text-white shadow-lg shadow-purple-500/30 transform transition-transform hover:scale-105">
            <Sparkles className="w-7 h-7" />
          </div>
          <div>
            <h1 className="text-2xl font-extrabold text-gray-900 tracking-tight">AI Financial Advisor</h1>
            <p className="text-gray-500 text-sm mt-0.5 flex items-center gap-1.5">
              <span>Powered by Google Gemini</span>
              <span className="relative flex h-2 w-2">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-green-400 opacity-75"></span>
                <span className="relative inline-flex rounded-full h-2 w-2 bg-green-500"></span>
              </span>
            </p>
          </div>
        </div>
        
        <div className="flex flex-col sm:flex-row gap-3 w-full sm:w-auto">
          <MonthYearPicker 
            month={month} 
            year={year} 
            onChange={handleDateChange} 
          />
          <button
            onClick={handleRefresh}
            disabled={isRefreshing || isLoading}
            className="flex-1 sm:flex-none inline-flex justify-center items-center px-4 py-2.5 text-sm font-semibold text-white bg-gray-900 rounded-xl hover:bg-gray-800 focus:ring-4 focus:ring-gray-200 transition-all shadow-md disabled:opacity-70 disabled:cursor-not-allowed group"
          >
            <RefreshCw className={`w-4 h-4 mr-2 ${isRefreshing ? 'animate-spin' : 'group-hover:rotate-180 transition-transform duration-500'}`} />
            Refresh Insight
          </button>
        </div>
      </div>

      {/* Outdated Data Banner */}
      {insightData?.isOutdated && !isLoading && !isRefreshing && (
        <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 flex items-start sm:items-center gap-3 animate-in slide-in-from-top-4">
          <AlertCircle className="w-5 h-5 text-amber-500 flex-shrink-0 mt-0.5 sm:mt-0" />
          <div className="flex-1">
            <h3 className="text-sm font-bold text-amber-800">New transaction data has been updated</h3>
            <p className="text-sm text-amber-700 mt-0.5">You should re-analyze to get the most accurate and up-to-date financial advice.</p>
          </div>
          <button
            onClick={handleRefresh}
            className="hidden sm:inline-flex px-3 py-1.5 bg-amber-100 hover:bg-amber-200 text-amber-700 text-xs font-bold rounded-lg transition-colors"
          >
            Re-analyze
          </button>
        </div>
      )}

      {/* Main Content Area */}
      <div className="bg-white rounded-3xl shadow-xl shadow-gray-200/40 border border-gray-100 overflow-hidden min-h-[500px] relative transition-all duration-300">
        
        {/* State 1: Loading Initial Data or Refreshing */}
        {(isLoading || isRefreshing) && (
          <div className="absolute inset-0 z-10 bg-white/80 backdrop-blur-sm flex flex-col items-center justify-center animate-in fade-in">
            <div className="relative">
              <div className="w-20 h-20 border-4 border-indigo-100 rounded-full animate-pulse"></div>
              <div className="w-20 h-20 border-4 border-indigo-500 rounded-full animate-spin absolute inset-0 border-t-transparent"></div>
              <Activity className="absolute inset-0 m-auto text-indigo-500 w-8 h-8 animate-pulse" />
            </div>
            <h3 className="mt-6 text-lg font-bold text-gray-800">AI is analyzing data</h3>
            <p className="text-gray-500 text-sm mt-2 max-w-xs text-center animate-pulse">
              Analyzing spending habits and summarizing the best advice for you...
            </p>
          </div>
        )}

        {/* State 2: Fallback No Data */}
        {isNoDataError && !isLoading && (
          <div className="h-full min-h-[500px] flex flex-col items-center justify-center text-center p-8">
            <div className="w-24 h-24 bg-gray-50 rounded-full flex items-center justify-center mb-6">
              <span className="text-5xl opacity-50">📂</span>
            </div>
            <h2 className="text-xl font-bold text-gray-800 mb-2">Not enough data to analyze</h2>
            <p className="text-gray-500 max-w-md mb-8">
              There are not enough transactions in {month}/{year} for the AI to evaluate and provide advice. Please add more transactions to start!
            </p>
          </div>
        )}

        {/* State 3: General Error */}
        {isError && !isNoDataError && !isLoading && (
          <div className="h-full min-h-[500px] flex flex-col items-center justify-center text-center p-8">
            <div className="w-20 h-20 bg-red-50 text-red-500 rounded-full flex items-center justify-center mb-6">
              <AlertCircle className="w-10 h-10" />
            </div>
            <h2 className="text-xl font-bold text-gray-800 mb-2">AI Connection Error</h2>
            <p className="text-gray-500 max-w-md mb-8">
              Cannot generate advice at this time due to a system error or busy AI server. Please try again later.
            </p>
            <button
              onClick={handleRefresh}
              className="px-6 py-3 bg-gray-900 text-white text-sm font-semibold rounded-xl hover:bg-gray-800 transition-colors"
            >
              Try again now
            </button>
          </div>
        )}

        {/* State 4: Data Available */}
        {!isLoading && !isError && insightData && (
          <div className="flex flex-col h-full">
            
            {/* Status Bar */}
            <div className="bg-gray-50/50 px-8 py-4 border-b border-gray-100 flex justify-between items-center">
              <div className="flex items-center gap-2.5 text-sm text-gray-500">
                <Clock className="w-4 h-4" />
                <span>
                  Updated {' '}
                  {insightData.updatedAt 
                    ? formatDistanceToNow(new Date(insightData.updatedAt), { addSuffix: true })
                    : 'just now'}
                </span>
              </div>
              
              {/* Optional indicator if typing */}
              {isTyping && (
                <span className="flex items-center gap-2 text-xs font-bold text-indigo-600 uppercase tracking-wider bg-indigo-50 px-3 py-1 rounded-full animate-pulse">
                  <span className="w-1.5 h-1.5 bg-indigo-600 rounded-full"></span>
                  AI is generating
                </span>
              )}
            </div>

            {/* Markdown Content */}
            <div className="p-8 md:p-10 flex-grow border-b border-gray-100">
              <article className="prose prose-indigo md:prose-lg max-w-none prose-headings:font-bold prose-h3:text-gray-800 prose-p:text-gray-600 prose-li:text-gray-600 prose-strong:text-indigo-900 prose-a:text-blue-600 pb-10">
                {displayedText ? (
                  <ReactMarkdown>{displayedText}</ReactMarkdown>
                ) : (
                  // Initial fallback while empty (e.g., right before typing starts)
                  <div className="space-y-4">
                    <div className="h-4 bg-gray-100 rounded w-3/4 animate-pulse"></div>
                    <div className="h-4 bg-gray-100 rounded w-1/2 animate-pulse"></div>
                  </div>
                )}
                
                {/* Blinking cursor effect at the end of text when typing */}
                {isTyping && (
                  <span className="inline-block w-1.5 h-5 bg-indigo-500 ml-1 translate-y-1 animate-ping"></span>
                )}
              </article>
            </div>
            
            {/* Interactive Chat Section */}
            <div className="p-6 md:p-8 bg-gray-50/30">
              <AiChatBox 
                onSendMessage={handleSendMessage} 
                isLoading={chatMutation.isPending} 
              />
            </div>
            
          </div>
        )}
      </div>
    </div>
  );
};

export default AiInsightPage;
